# Generated by Django 5.1.4 on 2025-01-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inquiry',
            options={'verbose_name_plural': 'Inquiries'},
        ),
        migrations.AlterModelOptions(
            name='rejectedinquiry',
            options={'verbose_name_plural': 'Rejected inquiries'},
        ),
    ]
