# Generated by Django 5.1.4 on 2025-01-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_alter_inquiry_options_alter_rejectedinquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('pa', 'Punjabi'), ('zh', 'Chinese'), ('yo', 'Yoruba')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='keyword',
            field=models.CharField(choices=[('FOOD', 'Food'), ('SHELTER', 'Shelter'), ('WATER', 'Water'), ('TOILET', 'Toilet'), ('WIFI', 'Wifi'), ('HELP', 'Help')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], max_length=16),
        ),
    ]
