# Generated by Django 4.2.18 on 2025-01-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0003_inquiry_language_alter_inquiry_keyword_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inquiry",
            name="keyword",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("SHELTER", "Shelter"),
                    ("WATER", "Water"),
                    ("TOILET", "Toilet"),
                    ("WIFI", "Wifi"),
                    ("HELP", "Help"),
                    ("MORE", "More"),
                ],
                max_length=20,
            ),
        ),
    ]
