# Generated by Django 4.2.18 on 2025-01-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0004_alter_inquiry_keyword"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InquiryResponse",
        ),
    ]
