# Generated by Django 4.2.18 on 2025-01-31 07:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0005_delete_inquiryresponse"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        choices=[
                            ("FOOD", "Food"),
                            ("SHELTER", "Shelter"),
                            ("WATER", "Water"),
                            ("TOILET", "Toilet"),
                            ("WIFI", "Wifi"),
                            ("HELP", "Help"),
                            ("MORE", "More"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("location_text", models.CharField(max_length=256)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("intersection", "Intersection"),
                            ("landmark", "Landmark"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processed", "Processed"),
                            ("error", "Error"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("pa", "Punjabi"),
                            ("zh", "Chinese"),
                            ("yo", "Yoruba"),
                        ],
                        max_length=3,
                    ),
                ),
                ("message", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.phonenumber",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Inquiries",
            },
        ),
        migrations.DeleteModel(
            name="Inquiry",
        ),
    ]
