# Generated by Django 4.2.18 on 2025-02-01 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0006_smsinquiry_delete_inquiry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_session_key", models.CharField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("flagged", "Flagged"),
                        ]
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("date_updated", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.phonenumber",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSFollowUpInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "keyword",
                    models.CharField(
                        choices=[("more", "More"), ("directions", "Directions")],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Follow-up inquiries",
            },
        ),
        migrations.CreateModel(
            name="SMSMessageOverflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "sms_followup",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.smsfollowupinquiry",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.conversation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UnresolvedSMSInquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=256)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.conversation",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Unresolved SMS Inquiries",
            },
        ),
        migrations.RemoveField(
            model_name="smsinquiry",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="smsinquiry",
            name="params",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="smsinquiry",
            name="keyword",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food"),
                    ("SHELTER", "Shelter"),
                    ("WATER", "Water"),
                    ("TOILET", "Toilet"),
                    ("WIFI", "Wifi"),
                    ("HELP", "Help"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="RejectedInquiry",
        ),
        migrations.AddField(
            model_name="smsmessageoverflow",
            name="sms_inquiry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.smsinquiry",
            ),
        ),
        migrations.AddField(
            model_name="smsinquiry",
            name="conversation",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to="sms.conversation",
            ),
            preserve_default=False,
        ),
    ]
