# Generated by Django 4.2.18 on 2025-02-01 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0007_conversation_smsfollowupinquiry_smsmessageoverflow_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsfollowupinquiry",
            name="params",
            field=models.JSONField(default=dict),
        ),
    ]
