# Generated by Django 4.2.18 on 2025-02-01 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0008_smsfollowupinquiry_params"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsinquiry",
            name="status",
        ),
    ]
