# Generated by Django 4.2.18 on 2025-02-07 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0009_remove_smsinquiry_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="date_updated",
            new_name="last_updated",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="phone_session_key",
        ),
    ]
