# Generated by Django 4.2.18 on 2025-02-10 00:09

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0010_rename_date_updated_conversation_last_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SMSFollowUpResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), null=True, size=None
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.conversation",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SMSInquiryResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sms.conversation",
                    ),
                ),
                (
                    "sms_inquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sms.smsinquiry"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="smsfollowupinquiry",
            name="keyword",
            field=models.CharField(
                choices=[
                    ("more", "More"),
                    ("info", "Info"),
                    ("directions", "Directions"),
                ],
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="SMSResponse",
        ),
        migrations.AddField(
            model_name="smsfollowupresponse",
            name="sms_follow_up",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sms.smsfollowupinquiry"
            ),
        ),
    ]
