# Generated by Django 4.2.18 on 2025-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0011_smsfollowupresponse_smsinquiryresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsfollowupinquiry",
            name="directions_text",
            field=models.TextField(null=True),
        ),
    ]
