# Generated by Django 4.2.18 on 2025-02-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0012_smsfollowupinquiry_directions_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsfollowupresponse",
            name="sms_follow_up",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sms.smsfollowupinquiry"
            ),
        ),
        migrations.AlterField(
            model_name="smsinquiryresponse",
            name="sms_inquiry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="sms.smsinquiry"
            ),
        ),
    ]
