# Generated by Django 4.2.18 on 2025-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0013_alter_smsfollowupresponse_sms_follow_up_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsfollowupresponse",
            name="directions",
            field=models.TextField(null=True),
        ),
    ]
