# Generated by Django 4.2.18 on 2025-04-28 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0004_delete_inquirycount"),
        ("sms", "0014_smsfollowupresponse_directions"),
    ]

    operations = [
        migrations.AddField(
            model_name="smsinquiry",
            name="inquiry_location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="geo.location",
            ),
        ),
    ]
