# Generated by Django 4.2.18 on 2025-04-28 04:23

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sms", "0015_smsinquiry_inquiry_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smsinquiry",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name="smsinquiry",
            name="location_text",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="smsinquiry",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("address", "Address"),
                    ("intersection", "Intersection"),
                    ("landmark", "Landmark"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
