version: '3.8'

services:
  web:
    build: .
    container_name: street_ninja_web
    depends_on:
      - db
      - redis
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "street_ninja.wsgi:application"]

  db:
    image: postgis/postgis:15-3.3
    container_name: street_ninja_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  redis:
    image: redis:alpine
    container_name: street_ninja_redis
    restart: always
    ports:
      - "6379:6379"

  celery-worker:
    build: .
    container_name: street_ninja_celery_worker
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: ["celery", "-A", "street_ninja", "worker", "--loglevel=info"]

  celery-beat:
    build: .
    container_name: street_ninja_celery_beat
    depends_on:
      - redis
      - db
    env_file:
      - .env
    command: ["celery", "-A", "street_ninja", "beat", "--loglevel=info"]

  nginx:
    image: nginx:alpine
    container_name: street_ninja_nginx
    depends_on:
      - web
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  postgres_data:
