version: '3.8'

services:
  web:
    user: "1000:1000"
    build: .
    container_name: street_ninja_web
    depends_on:
      - db
      - redis
    env_file:
      - .env.prod
    volumes:
      - .:/app
    command: ["gunicorn", "--bind", "127.0.0.1:8000", "--workers", "4", "--timeout", "120", "street_ninja_server.wsgi:application"]  # CHANGED: 0.0.0.0 → 127.0.0.1
    restart: always
    ports:
      - "127.0.0.1:8000:8000"  # ADDED: Localhost-only binding

  # REST OF YOUR FILE REMAINS EXACTLY THE SAME (db, redis, celery services)
  db:
    image: postgis/postgis:15-3.3
    container_name: street_ninja_db
    restart: always
    env_file:
      - .env.prod
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: street_ninja_redis
    restart: always
    ports:
      - "6380:6379"

  celery-worker:
    user: "1000:1000"
    build: .
    container_name: street_ninja_celery_worker
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    command: ["celery", "-A", "street_ninja_server", "worker", "--loglevel=info"]
    volumes:
      - ./log:/app/log

  celery-beat:
    user: "1000:1000"
    build: .
    container_name: street_ninja_celery_beat
    restart: always
    depends_on:
      - redis
      - db
    env_file:
      - .env.prod
    command: ["celery", "-A", "street_ninja_server", "beat", "--loglevel=info"]
    volumes:
      - ./log:/app/log

volumes:
  postgres_data: