services:

  test-runner:
    build: .
    depends_on:
      - db
      - redis
    env_file:
    - .env.ci
    command: ["pytest"]
    volumes:
      - .:/app

  db:
    image: postgis/postgis:15-3.3
    container_name: street_ninja_db
    restart: always
    env_file:
      - .env.ci
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5433:5432"  # Binding 5433 externally. So we don't conflict with local postgres installation.

  redis:
    image: redis:alpine
    container_name: street_ninja_redis
    restart: always
    ports:
      - "127.0.0.1:6380:6379"  # Binding 6380 externally
