# Generated by Django 4.2.18 on 2025-04-27 04:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_inquiries", models.IntegerField(default=0)),
                (
                    "location_type",
                    models.CharField(
                        choices=[
                            ("address", "Address"),
                            ("intersection", "Intersection"),
                            ("landmark", "Landmark"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location_text", models.CharField(max_length=255, unique=True)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("date_last", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
