# Generated by Django 4.2.18 on 2025-04-27 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0002_inquirycount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="total_inquiries",
        ),
    ]
