# Generated by Django 4.2.18 on 2025-04-27 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0003_remove_location_total_inquiries"),
    ]

    operations = [
        migrations.DeleteModel(
            name="InquiryCount",
        ),
    ]
