# Generated by Django 4.2.18 on 2025-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geo", "0005_neighborhood"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("address", "Address"),
                    ("intersection", "Intersection"),
                    ("landmark", "Landmark"),
                    ("neighborhood", "Neighborhood"),
                ],
                max_length=20,
            ),
        ),
    ]
