# Generated by Django 5.1.4 on 2025-01-18 16:12

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255, unique=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('address_extra_info', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('provides_meals', models.BooleanField()),
                ('provides_hampers', models.BooleanField()),
                ('meal_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('hamper_cost', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('delivery_available', models.BooleanField()),
                ('takeout_available', models.BooleanField()),
                ('wheelchair_accessible', models.BooleanField()),
                ('signup_required', models.BooleanField()),
                ('signup_phone_number', models.CharField(max_length=20, null=True)),
                ('signup_email', models.CharField(max_length=256, null=True)),
                ('requires_referral', models.BooleanField()),
                ('referral_agency_name', models.CharField(max_length=256, null=True)),
                ('referral_phone_number', models.CharField(max_length=20, null=True)),
                ('referral_email', models.CharField(max_length=256, null=True)),
                ('last_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shelters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category', models.CharField(choices=[('men', 'Men'), ('adults', 'Adults'), ('women', 'Women'), ('youth', 'Youth')], max_length=24)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('meals', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('carts', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
