# Generated by Django 5.1.4 on 2025-01-20 22:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shelter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('address', models.CharField(max_length=256, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Adults (all genders)', 'Adults'), ('Women', 'Women'), ('Youth (all genders)', 'Youth')], max_length=24)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('meals', models.BooleanField()),
                ('pets', models.BooleanField()),
                ('carts', models.BooleanField()),
                ('last_updated', models.DateTimeField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Shelters',
        ),
    ]
