# Generated by Django 5.1.4 on 2025-01-22 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_rename_last_updated_shelter_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='last_fetched',
            field=models.DateTimeField(null=True),
        ),
    ]
