# Generated by Django 5.1.4 on 2025-01-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_alter_shelter_last_fetched'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shelter',
            old_name='name',
            new_name='facility',
        ),
    ]
