# Generated by Django 5.1.4 on 2025-01-22 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_rename_name_shelter_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='address',
            field=models.CharField(max_length=256),
        ),
    ]
