# Generated by Django 4.2.18 on 2025-01-28 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_alter_shelter_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodprogram",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
