# Generated by Django 4.2.18 on 2025-02-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_foodprogram_is_active_shelter_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprogram",
            name="address",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="foodprogram",
            name="address_extra_info",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
