# Generated by Django 4.2.18 on 2025-02-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0009_alter_foodprogram_hamper_cost_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foodprogram",
            old_name="address",
            new_name="location_address",
        ),
        migrations.AddField(
            model_name="foodprogram",
            name="organization_name",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="foodprogram",
            name="program_status",
            field=models.CharField(default="Open", max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="foodprogram",
            name="program_name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
