# Generated by Django 4.2.18 on 2025-02-03 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0010_rename_address_foodprogram_location_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodprogram",
            name="program_population_served",
            field=models.TextField(null=True),
        ),
    ]
