# Generated by Django 4.2.18 on 2025-02-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0012_remove_foodprogram_last_updated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprogram",
            name="referral_email",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="foodprogram",
            name="signup_email",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
