# Generated by Django 4.2.18 on 2025-02-03 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0013_alter_foodprogram_referral_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foodprogram",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="foodprogram",
            name="location_address",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
