# Generated by Django 4.2.18 on 2025-02-03 19:07

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0014_alter_foodprogram_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DrinkingFountain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("location", django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ("is_active", models.BooleanField(default=True)),
                ("in_operation", models.CharField(max_length=64)),
                ("last_fetched", models.DateTimeField(null=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("pet_friendly", models.BooleanField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
