# Generated by Django 4.2.18 on 2025-02-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0015_drinkingfountain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="drinkingfountain",
            name="in_operation",
            field=models.CharField(default="year-round", max_length=64),
        ),
    ]
