# Generated by Django 4.2.18 on 2025-02-04 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0018_toilet_dataset"),
    ]

    operations = [
        migrations.AddField(
            model_name="toilet",
            name="is_wheelchair",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toilet",
            name="name",
            field=models.CharField(default="bleh", max_length=256),
            preserve_default=False,
        ),
    ]
