# Generated by Django 4.2.18 on 2025-06-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0020_publicwifi"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicwifi",
            name="name",
            field=models.CharField(default="", max_length=256),
        ),
    ]
