# Generated by Django 4.2.18 on 2025-06-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0021_publicwifi_name"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="publicwifi",
            constraint=models.UniqueConstraint(
                fields=("ssid", "location", "name"), name="unique_ssid_location_name"
            ),
        ),
    ]
