# Generated by Django 4.2.18 on 2025-06-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0022_publicwifi_unique_ssid_location_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="publicwifi",
            name="address",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="publicwifi",
            name="name",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
