# Generated by Django 4.2.18 on 2025-06-23 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0023_publicwifi_address_alter_publicwifi_name"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="publicwifi",
            name="unique_ssid_location_name",
        ),
        migrations.AddConstraint(
            model_name="publicwifi",
            constraint=models.UniqueConstraint(
                fields=("ssid", "location", "name", "address"),
                name="unique_ssid_location_name_address",
            ),
        ),
    ]
