# Generated by Django 4.2.18 on 2025-06-27 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0024_remove_publicwifi_unique_ssid_location_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toilet",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
