name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    env:
      DJANGO_SETTINGS_MODULE: street_ninja_server.test_settings
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build Docker images
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml build

      - name: Run tests
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml run --rm test-runner

      - name: Show web logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs web

      - name: Show DB logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs db

      - name: Show redis logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs redis

      - name: Show celery-worker logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs celery-worker

      - name: Show celery-beat logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs celery-beat

      - name: Show test-runner logs
        if: failure()
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml logs test-runner

      - name: Tear down
        run: docker compose --env-file .env.ci -f docker-compose.ci.yml down