name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Docker Compose version
        run: docker compose version

      - name: Build Docker images
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml build

      - name: Run tests
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml run --rm test-runner

      - name: Tear down
        run: docker-compose -f docker-compose.yml -f docker-compose.test.yml down